name: marvel
description: "A new Flutter project."
publish_to: "none"
version: 0.1.0

environment:
  sdk: ">=2.12.0 <4.0.0"

dependencies:
  carousel_slider: 4.2.1
  cupertino_icons: 1.0.6
  delayed_display: ^2.0.0
  fancy_drawer: ^2.0.0
  flutter:
    sdk: flutter
  flutter_login: ^5.0.0
  youtube_player_flutter: ^8.1.2

dev_dependencies:
  flutter_test:
    sdk: flutter
flutter:
  uses-material-design: true

  assets:
    - assets/images/
